name: Infra CI (Terraform + Ansible)

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check repo
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          pwd
          ls -la

      - name: Detect Terraform directory
        id: detect
        run: |
          if [ -d "terraform" ] && ls terraform/*.tf >/dev/null 2>&1; then
            echo "TF_WORKDIR=terraform" >> $GITHUB_ENV
            echo "Found terraform/ with .tf files"
          elif ls *.tf >/dev/null 2>&1; then
            echo "TF_WORKDIR=." >> $GITHUB_ENV
            echo "Found .tf files in repo root"
          else
            echo "No .tf files found in terraform/ or repo root"
            exit 1
          fi

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd "$TF_WORKDIR"
          terraform init -input=false

      - name: Terraform Fmt
        run: |
          cd "$TF_WORKDIR"
          terraform fmt -check -recursive

      - name: Terraform Validate
        run: |
          cd "$TF_WORKDIR"
          terraform validate

      - name: Terraform Plan
        run: |
          cd "$TF_WORKDIR"
          terraform plan -input=false

  ansible:
    runs-on: ubuntu-latest
    needs: terraform            # run after TF job; remove if you want parallel
    defaults:
      run:
        working-directory: ansible
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Syntax check (localhost only)
        run: ansible-playbook -i localhost, -c local main.yml --syntax-check