name: Infra

on:
  push: { branches: [ main ] }
  workflow_dispatch: {}

jobs:
  tf:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: terraform } }
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -input=false
      - run: terraform fmt -recursive
      - run: terraform validate
      - run: terraform plan -input=false
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        run: terraform apply -auto-approve -input=false

  ansible:
    runs-on: ubuntu-latest
    needs: tf
    defaults: { run: { working-directory: ansible } }
    steps:
      - uses: actions/checkout@v4
      - run: |
          python -m pip install --upgrade pip
          pip install ansible
      - run: ansible-playbook -i localhost, -c local main.yml --syntax-check
