name: Infra CI (Terraform + Ansible)

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -input=false

      - name: Apply (only on manual runs)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        working-directory: terraform
        run: terraform apply -auto-approve -input=false

  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    defaults:
      run:
        working-directory: ansible
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Syntax check (localhost only)
        run: ansible-playbook -i localhost, -c local main.yml --syntax-check
